<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FlaUI.Core" />
    <PackageReference Include="FlaUI.UIA3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Clients\WpfClient\WpfClient.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
