<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\AI.Adapters\AI.Adapter.Ollama\AI.Adapter.Ollama.csproj" />
    <ProjectReference Include="..\..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\..\src\Presentation\Presentation.csproj" />
  </ItemGroup>
</Project>
