<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\AI.Adapters\AI.Adapter.Ollama\AI.Adapter.Ollama.csproj" />
    <ProjectReference Include="..\..\Engine.Adapters\Engine.Adapter.PInvoke\Engine.Adapter.PInvoke.csproj" />
    <ProjectReference Include="..\..\Presentation\Presentation.csproj" />
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	</ItemGroup>
</Project>
